# -*- coding: utf-8 -*-
"""Grade Calculator System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Rap6QGZCjaK6XTQi_S1G3t5yKWrhkSE
"""

#Creating Grade calculator

import pandas as pd

class GradeSystem():
  def __init__(self, course_name, student_name, student_ID, grade):
    self.course_name = course_name
    self.student_name = student_name
    self.student_ID = student_ID
    self.grade = grade

course_name =input("Please insert course name: ")
student_name = input("Insert a student name : ") 
student_id = int(input("Insert your student ID : "))
grade = int(input("Insert assesment score: "))

def get_grade(get_letter_grade):
    if get_letter_grade >= 89.5:
      print(f"{student_name}, {student_ID} PASSED {course_name} with A")
    elif get_letter_grade <= 89.49 and get_letter_grade >= 79.5:
      print(f"{student_name}, {student_ID} PASSED {course_name} with A")
    elif get_letter_grade <= 79.49 and get_letter_grade >= 69.5:
      print(f"{student_name}, {student_ID} PASSED {course_name} with A")
    elif get_letter_grade <= 69.49 and get_letter_grade >= 59.5:
      print(f"{student_name}, {student_ID} PASSED {course_name} with A")
    else:
      print("FAILED with F")
        
get_grade(84)

student_exam_result = {'student_name': ["Jackie", "Kate", "Ryan", "Martha"],
                           'student_surname': ["Wilson", "Perry", "Gosling", "Stewart"],
                           'student_id': [780954, 789467, 782325, 783566],
                           'Course': ["Biology", "Math", "Algebra", "Physics"],
                           'Point': [84, 92, 67, 40],
                           'Grade': ["Passed", "Passed", "Passed", "Failed"]}
df =pd.DataFrame(student_exam_result)
print(df)